# Generated by Django 5.2.12 on 2026-09-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(choices=[("login", "Login"), ("logout", "Logout"), ("not_logged_1day", "Not logged in for 1 day"), ("not_logged_1week", "Not logged in for 1 week"), ("password_reset", "Password reset"), ("order_placed", "Order placed")], max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp"), ("email", "Email"), ("web_push", "Web Push")], max_length=20)),
                ("is_enabled", models.BooleanField(default=True)),
                ("title", models.CharField(blank=True, help_text="For Email subject and Web Push title", max_length=200)),
                ("body", models.TextField(help_text="Message body for all channels")),
                ("whatsapp_template_name", models.CharField(blank=True, help_text="Template name on Meta", max_length=200)),
                ("whatsapp_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("trigger", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="notifications.trigger")),
            ],
            options={"ordering": ["trigger", "channel"], "unique_together": {("trigger", "channel")}},
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient", models.CharField(help_text="Phone number, email, or user ID", max_length=255)),
                ("status", models.CharField(choices=[("sent", "Sent"), ("failed", "Failed"), ("pending", "Pending")], default="pending", max_length=20)),
                ("message", models.TextField(blank=True)),
                ("external_id", models.CharField(blank=True, help_text="ID from external API", max_length=255)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="notifications.notificationtemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip_address", models.CharField(blank=True, max_length=50)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("logged_in_at", models.DateTimeField(auto_now_add=True)),
                ("logged_out_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-logged_in_at"]},
        ),
    ]
